// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package repository

import (
	"database/sql"
)

type TreeFolder struct {
	ID        int32         `db:"id"`
	Name      string        `db:"name"`
	IsFolder  sql.NullBool  `db:"is_folder"`
	ParentID  sql.NullInt32 `db:"parent_id"`
	CreatedAt sql.NullTime  `db:"created_at"`
	UpdatedAt sql.NullTime  `db:"updated_at"`
}
